"""initial schema

Revision ID: 1ead7e90149c
Revises: 
Create Date: 2026-09-10 14:12:02.465787

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ead7e90149c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('REQUEST', 'RESPONSE', 'TOOL_CALL', 'TOOL_RESULT', 'POLICY_RELOAD', 'ERROR', name='auditeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('SYSTEM', 'USER', 'TOOL', 'UNKNOWN', name='sourcetype', native_enum=False, length=16), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_session_id'), ['session_id'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('layer', sa.String(length=8), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'CONFIRM', 'BLOCK', name='riskaction', native_enum=False, length=16), nullable=False),
    sa.Column('input_snippet', sa.Text(), nullable=True),
    sa.Column('matched', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_session_id'), ['session_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_agent_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_created_at'))

    op.drop_table('risk_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
